image: Visual Studio 2019

environment:
 matrix:
  - solution_path: Task3\Task3.sln
test_15_05_20
before_build:
  - nuget restore %solution_path%

build_script:
test_15_05_20
- msbuild %solution_path%

