image: Visual Studio 2019

environment:
 matrix:
  - solution_path: Task3\Task3.sln
  - solution_path: SimpleFunctions\SimpleFunctions.sln

before_build:
  - nuget restore %solution_path%

build_script:
- msbuild %solution_path%
